### ISSUE TITLE
Black screen with video clip screensaver

### ISSUE THREAD

**Issue by Pnumekin** [beudbeud/artbookcrt-240p#4]
Your theme is very nice but I have a problem with Screensaver. I want to use video clips as screensaver and it's working with my other theme but when using yours I have a black screen.

Step to reproduce 
Apply your theme
Select video clip as screensaver
Wait and only a black screen appears

Expected
Videos clips should play

Using Recalbox 9.2 patron 4.1

**Comment by beudbeud** [comment]
Hi thanks for the report, i fix it i will publish new version 2.4
